from falcor import *

def render_graph_OptixDenoiser():
    g = RenderGraph("OptixDenoiser")
    loadRenderPassLibrary("AccumulatePass.dll")
    loadRenderPassLibrary("GBuffer.dll")
    loadRenderPassLibrary("OptixDenoiser.dll")
    loadRenderPassLibrary("WavefrontPathTracer.dll")
    loadRenderPassLibrary("ToneMapper.dll")
    GBufferRT = createPass("GBufferRT")
    g.addPass(GBufferRT, "GBufferRT")
    AccumulatePass = createPass("AccumulatePass")
    g.addPass(AccumulatePass, "AccumulatePass")
    ToneMappingPass = createPass("ToneMapper", {'autoExposure': False, 'operator': ToneMapOp.Aces, 'clamp': True})
    g.addPass(ToneMappingPass, "ToneMappingPass")
    WavefrontPathTracer = createPass("WavefrontPathTracer", {'params': PathTracerParams(useVBuffer=0)})
    g.addPass(WavefrontPathTracer, "WavefrontPathTracer")
    OptixDenoiser = createPass("OptixDenoiser")
    g.addPass(OptixDenoiser, "OptixDenoiser")
    g.addEdge("GBufferRT.posW", "WavefrontPathTracer.posW")
    g.addEdge("GBufferRT.normW", "WavefrontPathTracer.normalW")
    g.addEdge("GBufferRT.tangentW", "WavefrontPathTracer.tangentW")
    g.addEdge("GBufferRT.faceNormalW", "WavefrontPathTracer.faceNormalW")
    g.addEdge("GBufferRT.viewW", "WavefrontPathTracer.viewW")
    g.addEdge("GBufferRT.diffuseOpacity", "WavefrontPathTracer.mtlDiffOpacity")
    g.addEdge("GBufferRT.specRough", "WavefrontPathTracer.mtlSpecRough")
    g.addEdge("GBufferRT.emissive", "WavefrontPathTracer.mtlEmissive")
    g.addEdge("GBufferRT.matlExtra", "WavefrontPathTracer.mtlParams")
    g.addEdge("WavefrontPathTracer.color", "AccumulatePass.input")
    g.addEdge("AccumulatePass.output", "ToneMappingPass.src")
    g.addEdge("ToneMappingPass.dst", "OptixDenoiser.color")
    g.addEdge("WavefrontPathTracer.albedo", "OptixDenoiser.albedo")
    g.addEdge("GBufferRT.normW", "OptixDenoiser.normal")
    g.markOutput("AccumulatePass.output")
    g.markOutput("OptixDenoiser.output")
    return g

OptixDenoiser = render_graph_OptixDenoiser()
try: m.addGraph(OptixDenoiser)
except NameError: None
